### ISSUE TITLE
my use-case is defunct now…

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#16]
I sure hope this whole exercise has been useful (I certainly have learned a good bit about some things). My main use-case is now prohibited due to blocked chars:

    nosuspend jack_capture -p system:capture* -c 1 -mp3b 48 -fn ~/Desktop/Andrew-`date +%Y-%m-%d`.mp3

I've figured out that `:` and `*` are prohibited. I don't know how to specify the port without those symbols. Do you know of a way?

Otherwise, I'm thinking that the solution I'll need (aside from giving up and just dealing with human error in turning on or off power management manually) may involve figuring out the CLI method for turning off KDE's power management instead of doing it at the systemd level…

**Comment by brummer10** [comment]
I've add those signs to the whitelist, as they are non critical.
The only critical sign in your line is   `    

if you really need it, you need to remove it by yourself from line 86
const char nogo[] = "&;|$><`\\!";

**Comment by wolftune** [comment]
something is wrong with your comment as it reads "the only critical sign in your line is if…" and doesn't show what the critical sign is. And I'm further confused because the update now runs my line completely with no errors.

At any rate, at this point, the question I have is how much it's worth continued work on this. If it can be made usable to others and is *okay* for wider promotion, great. If it's a quirky questionable thing we shouldn't really promote, then maybe it doesn't make too much sense… I wish I knew how to CLI adjust the power management in KDE in a way that would actually be effective here.

**Comment by brummer10** [comment]
as soon (if ever) we get a configure option for systemd-inhibit, we could remove the setuid requirement and been full save. 
 https://github.com/systemd/systemd/issues/949

**Comment by brummer10** [comment]
slowly we get somewhere  more secure, check out the last commit . .  .

**Comment by wolftune** [comment]
it works for me still

**Comment by wolftune** [comment]
I have no remaining issue here. Closing this. But if newer updates potentially make it safer to whitelist more characters, that *could* be nice… at the moment I have no need for that, but someone might ever appreciate that if it became safe.
