### ISSUE TITLE
allow swapping the policy file?

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#19]
I tried the `make relaxed` and `sudo make install` options and am still being asked for pass every time I use nosuspend

**Comment by brummer10** [comment]
You need to run `sudo make uninstall` to switch between the versions. 
I've put a test in the makefile which check if the policy file is installed and only install a new one when not found. 
Maybe I better remove this check and install new anyway, to avoid such confusion.

**Comment by wolftune** [comment]
a ha, well, that worked. I think if it's no problem to swap the policy file, even if it's just a duplicate, then it makes sense to just allow the swap to happen without uninstalling first.

**Comment by wolftune** [comment]
is there a security issue of making it easier to swap policy files? Telling people to uninstall in order to swap is okay if there's a reason to go that way

**Comment by brummer10** [comment]
No, I just had it in for develop reasons, I just have remove this check, so switch between versions is now possible without involve uninstall.
