### ISSUE TITLE
enable tab completion after nosuspend?

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#2]
Is there a way to run nosuspend and still be able to then use tab-completion as normal for entering whatever the normal command is after that?

**Comment by brummer10** [comment]
I'll check if it is possible

**Comment by brummer10** [comment]
Yes, I've added a bash completion script (no_suspend) which will install in 
/etc/bash_completion.d
this allow to use the normal autocomplete function from bash. 
When fresh installed, you may open a new terminal to reload the bash_completion files, or load it explicit with the command 
.  /etc/bash_completion.d/no_suspend

**Comment by wolftune** [comment]
works! yay!
