### ISSUE TITLE
doesn't work with commands with args

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#4]
`nosuspend jack_capture` works fine

but `nosuspend jack_capture -p system:capture* -c 1` gives

```
nosuspend: invalid option -- 'p'
nosuspend blocks computer suspend while another command-line operation is running
Usage: nosuspend  executable arg arg2 . .
```

it appears that plain args may be used but args with dashes do not work. I tried `nosuspend --` etc. but that didn't work.

**Comment by brummer10** [comment]
you need to escape the command-line in order to hand over  parameters with dashes to jack_capture, otherwise getopt will grab them and hand them to nosuspend.
`nosuspend 'jack_capture -p system:capture* -c 1'`

**Comment by brummer10** [comment]
Okay, I've removed getopt and handle the -h, --help option direct now.
Now escaping isn't needed any more.

**Comment by wolftune** [comment]
Well, it definitely works now, but ctrl-C and enter no longer stop jack_capture. It sort of glitches and adds a new line where it continues to show the input meter. I was only able to stop it by closing the terminal entirely.

**Comment by brummer10** [comment]
Okay, I've included a workaround for this, should work now.

**Comment by wolftune** [comment]
Interesting. If I do ctrl-C, it says ` ...terminated.` but doesn't return me to prompt until I ctrl-C again. But if I hit Enter, it finishes and returns me to the prompt. I can certainly get used to using enter, and ctlr-C twice is usable.

Thanks again, and hope this becomes useful to others too (I'll be telling people about it!)

**Comment by brummer10** [comment]
> Interesting. If I do ctrl-C, it says ...terminated. but doesn't return me to prompt until I ctrl-C again.

Solved now as well. (was a timing issue)

> Thanks again, and hope this becomes useful to others too (I'll be telling people about it!)

Thanks, I'm glad it is useful for you.
