### ISSUE TITLE
interesting dialog…

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#5]
![screenshot_20161127_113322](https://cloud.githubusercontent.com/assets/2801853/20651208/91a15568-b495-11e6-91ef-4770537086c6.png)

after running nosuspend for a while.

I could dismiss this and it didn't stop me from using other windows.

**Comment by brummer10** [comment]
Yes, that's how nosuspend work. It set's the systemd inhibit flag with root rights, so, only root is allowed to suspend the system. systemd inform you about that a system service wont to suspend the system with this window, and ask you:

> "Are you root, should we ignore your previous request to no-suspend the system and allow this to the service or not?" 

You could ignore the question, cancel it, or, at your wish, suspend the system now.
That works, regardless which service ask for suspend the system, as well, when you close your laptop, for example.

**Comment by wolftune** [comment]
Sounds good, I just ignored it / closed it a couple times. I suppose an ideal might be to suppress the notification somehow, but I'm not even certain that's a good idea. I suppose that's a design question and then also a question whether that's even feasible or easy enough to be even a someday-maybe item.

**Comment by wolftune** [comment]
If nothing else, it seems it should be added to the documentation so people know that they can ignore/cancel/suspend and that this notification is normal.

**Comment by brummer10** [comment]
> If nothing else, it seems it should be added to the documentation so people know that they can ignore/cancel/suspend and that this notification is normal.

Yes, may you help me out here and add/rework it for the Readme.md?

**Comment by wolftune** [comment]
sure
