### ISSUE TITLE
nosuspend mpv fails to let keyboard commands work

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#8]
If I run mpv with nosuspend as in `nosuspend mpv filename` and it's an audio file so that no window is opened (it's just in the terminal), the key commands for mpv don't work.

**Comment by brummer10** [comment]
did it work when you run `fg %- ` in the terminal?

**Comment by wolftune** [comment]
I'm not sure how to do that. When I tap a key while mpv is playing in this context, I see stuff like `[[C^`

I.e. in this case, I don't have a usable prompt

**Comment by brummer10** [comment]
oh yea. Puh, I tried it and well, don't exactly know why it ain't work. As a workaround you could run, for example `nosuspend  gnome-terminal` ( or your preferred terminal)  to open a new terminal, were you run then mpv. As long you keep the new terminal, nosuspend will do it's job.

**Comment by wolftune** [comment]
Sure, and I could otherwise turn off power-management. But if there's any solution to the bug, that would be ideal. Could just leave the ticket open indefinitely if the fix isn't understood. No big deal. Figured it would be helpful to report anyway.

**Comment by brummer10** [comment]
Yes, thanks for reporting, I'll have a look at the issue later (properly next month). 

regards
hermann

**Comment by brummer10** [comment]
So I've found the time to add a solution for this issue, just, it add a new dependency to the program `screen`. Make sure you've installed it, and try please if it works now the right way. 

regards
hermann

**Comment by wolftune** [comment]
It works! Thanks!
