### ISSUE TITLE
tab completion for args like files

### ISSUE THREAD

**Issue by wolftune** [brummer10/nosuspend#9]
I get full tab completion for, e.g. `nosuspend mpv` but not for `nosuspend mpv filename.opus`.

I can tab-complete `mpv filename.opus` and then jump to the beginning to add in nosuspend, but it would be ideal if tab-completion of the filename worked when entering everything sequentially.

**Comment by brummer10** [comment]
okay, done. You'll need to restart your terminal after install to activate it. 

regards
hermann

**Comment by wolftune** [comment]
w00t! it works! This this is superb and deserves some wider promotion!
